### ISSUE TITLE
dpkg-deb on mac OS 12.4

### ISSUE THREAD

**Issue by syto203** [itsnebulalol/permasigner#10]
The supplied dpkg-deb from procurces results in this error:
```
[*] Packaging the deb file...
dyld[4327]: Library not loaded: @rpath/libmd.0.dylib
  Referenced from: /Users/syto203/Documents/Repositories/permasigner/dpkg-deb
  Reason: tried: '/opt/procursus/lib/libmd.0.dylib' (no such file), '/opt/procursus/lib/libmd.0.dylib' (no such file), '/usr/local/lib/libmd.0.dylib' (no such file), '/usr/lib/libmd.0.dylib' (no such file)
```

linking the one already installed (brew or macports) to the path of permasigner instead of downloading from procurses mitigates this error.

**Comment by itsnebulalol** [comment]
That’s interesting, it’s expecting for procursus
@verygenericname is there another macOS dpkg-deb? or will we have to use brew’s

**Comment by itsnebulalol** [comment]
Leaving this open for now, but I have made it require brew dpkg on macOS.

**Comment by syto203** [comment]
Macports has it too but I didn’t try it. Better to mention both in case a user has either.

**Comment by itsnebulalol** [comment]
I'd rather not have people use MacPorts. Brew isn't great but it's way better than MacPorts.
If people use MacPorts they probably know they can use that too.
