### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by Am1nCmd** [itsnebulalol/permasigner#11]
✘ am1ncmd@Hack1ntosh  ~/permasigner   main  python3 main.py 
IPA Permasigner | Version main-5fe80e9
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[*] dpkg-deb not found, downloading.

[?] Would you like to use an IPA stored on the web, or on your system? [external, local] external
[*] Created temporary directory.

[?] Paste in the *direct* path to an IPA online: https://github.com/BandarHL/BHTwitter/releases/download/2.9.6/Twitter_9.14_BHTwitter_2.9.6.ipa
[*] Downloading file...

[*] Unzipping IPA...

[*] Reading plist...
Found plist!
Executable found.
Found information about the app!

[*] Preparing deb file...
Making directories...
Copying deb file scripts and control...
Copying app files...
Changing deb file scripts permissions...
Changing app executable permissions...

[*] Signing app...
Signing with ldid...

[*] Packaging the deb file...
Traceback (most recent call last):
  File "/Users/am1ncmd/permasigner/main.py", line 332, in <module>
    main(args)
  File "/Users/am1ncmd/permasigner/main.py", line 319, in main
    subprocess.run(f"./dpkg-deb -Zxz --root-owner-group -b {tmpfolder}/deb output/{app_name}.deb".split(), stdout=subprocess.DEVNULL)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './dpkg-deb'
 ✘ am1ncmd@Hack1ntosh  ~/permasigner   main 

**Comment by itsnebulalol** [comment]
I’ll fix it later, but for now you can remove the ./ in that part of the code

**Comment by itsnebulalol** [comment]
Pull new changes, i’ve fixed it
