### ISSUE TITLE
Logouts after closing the Apps

### ISSUE THREAD

**Issue by iammanpreetsingh** [itsnebulalol/permasigner#12]
I am to be honest not sure, why this is happening. 
Yesterday I tried Twitter, but it's logging me out every time I open the app. So I thought making the deb of twitter, maybe Twitter has some issues. 
So I ignored that. 

But Today, I installed Instagram, and the same thing is happening. I sign in. Close the App. Then I again opened the app and I am on the login screen. 

Why this is happening? 

iPhone 8 iOS14.8
Used Checkra1n. 

If you want, we can do testing.

**Comment by itsnebulalol** [comment]
I had this issue with sideloading Twitter too, unfortunately it’s not just an issue with this, it’s an issue with every signing service I’ve used except for Signulous.

For Instagram, you might be able to use https://github.com/opa334/IGSideloadFix although i’ve never tried it.

Tell me if it works!

**Comment by itsnebulalol** [comment]
Seeing your other issue, try to remove `—codesign` from the command. ldid will keep the entitlements instead of replacing them.

**Comment by itsnebulalol** [comment]
Will close this as it's not something _I_ can fix with the script.

**Comment by itsnebulalol** [comment]
Should be *partially* fixed in commit 587e05e.

**Comment by itsnebulalol** [comment]
Doesn't seem to be an issue with ldid as shown in #33, no idea whats going wrong
