### ISSUE TITLE
[-] That file does not exist! Make sure you're using a direct path to the IPA file.

### ISSUE THREAD

**Issue by iammanpreetsingh** [itsnebulalol/permasigner#13]
Well, I have found a bug in the script with the solution too. 

It doesn't recognise .ipa file as an .ipa file. 

It only works when if I rename the ".ipa" to ".IPA" (Capital letters).

![Error](https://user-images.githubusercontent.com/41124506/177650382-94b7e64b-d5ef-48bd-8bbc-62766977869f.png)

**Comment by itsnebulalol** [comment]
That is… not a bug I thought it would have. It checks if it exists using `os.path.exists`, and doesn’t check if it’s an ipa until later steps…
