### ISSUE TITLE
[feature] automatically pull apps from a folder

### ISSUE THREAD

**Issue by Baggette** [itsnebulalol/permasigner#17]
Maybe add a feature where you place the ipa's in a folder and it indexes them and you select the ipa you want to sign from a numbered menu

**Comment by itsnebulalol** [comment]
Interesting idea. I could probably add a `—folder` argument so provide a folder with a whole bunch of ipas. I was already going to add `—url` and `—path` so it could work with a Siri Shortcut on iOS.

Only issue with this is i’d have to make the whole program run on a loop, which isn’t a big deal but will require some code changing.

**Comment by c-hri-s** [comment]
+1 for this

It would be great to give the tool a folder of ipas and have it work through them sequentially. That way I could drag ipas to a folder, run docker and then end up with a signed folder without needing to rerun it per-file and enter the filename

**Comment by itsnebulalol** [comment]
Added in 85501f1 with the -f (--folder) argument.
