### ISSUE TITLE
Monterey 12.4 Issue

### ISSUE THREAD

**Issue by FreQRiDeR** [itsnebulalol/permasigner#18]
latest main.py hangs before prompt to pick external or local .ipa. prompt never happens? Works on my iPhone. Worked fine before today's latest update? I deleted old permasigner folder and re-Gitted it. 

Terminal Output:

terramoda@terraMODAs-Mac-Pro permasigner % python3 main.py
IPA Permasigner | Version main-244b6dc
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

----------------------------------------------------------------------------------------------------

Just hangs there?

**Comment by itsnebulalol** [comment]
Run `git pull` and try again

**Comment by FreQRiDeR** [comment]
same....

------------------------------
terramoda@terraMODAs-Mac-Pro permasigner % python3 main.py
IPA Permasigner | Version main-cec1e5a
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

**Comment by FreQRiDeR** [comment]
OK, after some time I got a warning ldid was broken or outdated.  Installing ldid via brew fixed it. You can close the issue. Thanks!

**Comment by itsnebulalol** [comment]
Don’t use brew ldid! It won’t work with the script.

I’m currently adding debug statements to find out where it’s failing.

Make sure to remove brew’s ldid

**Comment by itsnebulalol** [comment]
Can you please run `git pull` and run `python3 main.py --debug`? Then show me the output.

**Comment by FreQRiDeR** [comment]
Here is the output. I'm using brew installed dpkg, ldid and it's working? I don't have either in permasigner dir, running from PATH. 
----------------------------------

terramoda@terraMODAs-Mac-Pro ~ % cd permasigner
terramoda@terraMODAs-Mac-Pro permasigner % python3 main.py --debug
IPA Permasigner | Version main-cec1e5a
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[?] Would you like to use an IPA stored on the web, or on your system? [external, local] local
[*] Created temporary directory.

[?] Paste in the path to an IPA in your file system: /Users/terramoda/Documents/IPA/Poison-202 (v2.5.4 v2.5.4.0 unk PI 64bit os100 ok14)-user_hidden.bfi.ipa

[*] Unzipping IPA...

[*] Reading plist...
Found plist!
Executable found.
Found information about the app!

[*] Preparing deb file...
Making directories...
Copying deb file scripts and control...
Copying app files...
Changing deb file scripts permissions...
Changing app executable permissions...

[*] Signing app...
Signing with ldid...
usage: ldid -S[entitlements.xml] <binary>
   ldid -e MobileSafari
   ldid -S cat
   ldid -Stfp.xml gdb

[*] Packaging the deb file...
[DEBUG] Running command: dpkg-deb -Zxz --root-owner-group -b /var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmp5vgrvxqi/deb output/Poison-202.deb

[*] We are finished!
[*] Copy the newly created deb from the output folder to your jailbroken iDevice and install it!
[*] The app will continue to work when rebooted to stock.
terramoda@terraMODAs-Mac-Pro permasigner % 


------------------------
ls of my permasigner dir
------------------------

terramoda@terraMODAs-Mac-Pro permasigner % ls -l
total 112
-rw-r--r--  1 terramoda  staff    774 Jul  8 14:09 Dockerfile
-rw-r--r--  1 terramoda  staff   1514 Jul  8 14:09 LICENSE
-rw-r--r--  1 terramoda  staff   3641 Jul  8 14:09 README.md
-rw-r--r--  1 terramoda  staff    316 Jul  8 14:09 control
-rw-r--r--  1 terramoda  staff   5257 Jul  8 14:09 dev_certificate.p12
-rw-r--r--  1 terramoda  staff    787 Jul  8 14:09 entitlements.plist
-rw-r--r--  1 terramoda  staff  14104 Jul  8 14:49 main.py
drwxr-xr-x  4 terramoda  staff    128 Jul  8 19:39 output
-rw-r--r--  1 terramoda  staff     49 Jul  8 14:09 postinst
-rw-r--r--  1 terramoda  staff     49 Jul  8 14:09 postrm
-rw-r--r--  1 terramoda  staff    136 Jul  8 14:09 requirements.txt
drwxr-xr-x  6 terramoda  staff    192 Jul  8 14:10 utils
terramoda@terraMODAs-Mac-Pro permasigner %

**Comment by itsnebulalol** [comment]
Yes, it runs, but it fails to sign as shown where it says signing with ldid.

I also said to run `git pull` before you did it.

**Comment by FreQRiDeR** [comment]
My apologies, you did say pull first. Here is the new output. I deleted brew's ldid, ran the script in debug and after dl'ing ldid it seems to have worked! I don't believe there was an issue at all! except for perhaps, me! LoL

Term Output:

----------------------

Last login: Fri Jul  8 21:03:07 on ttys000
terramoda@terraMODAs-Mac-Pro ~ % cd permasigner
terramoda@terraMODAs-Mac-Pro permasigner % python3 main.py --debug
IPA Permasigner | Version main-dd11064
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[DEBUG] Checking if command ldid is in PATH...
[DEBUG] On macOS x86_64, ldid not found...
[DEBUG] Checking ldid hash...
[DEBUG] ldid hash successfully verified.
[DEBUG] Checking if command dpkg-deb is in PATH...
[?] Would you like to use an IPA stored on the web, or on your system? [external, local] local
[*] Created temporary directory.

[?] Paste in the path to an IPA in your file system: /Users/terramoda/Documents/IPA/StrelokPro.ipa

[*] Unzipping IPA...

[*] Reading plist...
Found plist!
Executable found.
Found information about the app!

[*] Preparing deb file...
Making directories...
Copying deb file scripts and control...
Copying app files...
Changing deb file scripts permissions...
Changing app executable permissions...

[*] Signing app...
Signing with ldid...
[DEBUG] Checking if command ldid is in PATH...

[*] Packaging the deb file...
[DEBUG] Running command: dpkg-deb -Zxz --root-owner-group -b /var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpl1ovvhii/deb output/StrelokPro.deb
[DEBUG] Checking if command dpkg-deb is in PATH...

[*] We are finished!
[*] Copy the newly created deb from the output folder to your jailbroken iDevice and install it!
[*] The app will continue to work when rebooted to stock.
terramoda@terraMODAs-Mac-Pro permasigner %

**Comment by itsnebulalol** [comment]
Yup, it worked this time!
