### ISSUE TITLE
NameError: name 'args' is not defined

### ISSUE THREAD

**Issue by dxwil** [itsnebulalol/permasigner#19]
`ubuntu@ubuntu:~/permasigner$`` sudo python3 main.py
IPA Permasigner | Version main-2a4362e
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

Traceback (most recent call last):
  File "/home/ubuntu/permasigner/main.py", line 311, in <module>
    main(args)
  File "/home/ubuntu/permasigner/main.py", line 61, in main
    if not LdidHash.check_linux_64():
  File "/home/ubuntu/permasigner/utils/hash.py", line 26, in check_linux_64
    if args.debug:
NameError: name 'args' is not defined
`

**Comment by itsnebulalol** [comment]
Will be fixing this, hold on!

**Comment by dxwil** [comment]
Thanks, let me know then

**Comment by itsnebulalol** [comment]
Could you please run `git pull` and try again?

**Comment by dxwil** [comment]
Looks like it works now, thanks!
