### ISSUE TITLE
Me again... ldid ios issue this time. 

### ISSUE THREAD

**Issue by FreQRiDeR** [itsnebulalol/permasigner#20]
So after a pull I tried new script and ldid errored with a libplist-2.0.3.dyld not found? 

I fixed it earlier by installing libplist3. That didn’t work so I copied and renamed libplist3 to libplist-2.0.3.dylib and it works now? Not sure but I expect this to be a flaw in precirsus’ ldid for ios? I have notified team as well. (I installed ldid via Zebra pkg manager and then copied it to permasigner directory. This worked before. Maybe cause of issue? I don’t know??)

Term Output:

iPhone:~ mobile% cd permasigner
iPhone:~/permasigner mobile% ./ldid
dyld: Library not loaded: /usr/lib/libplist-2.0.3.dylib
  Referenced from: /private/var/mobile/permasigner/./ldid
  Reason: image not found
zsh: abort      ./ldid
iPhone:~/permasigner mobile% 
iPhone:~/permasigner mobile% apt info ldid    
Package: ldid
Version: 2.1.5-procursus3
Priority: optional
Section: Development
Maintainer: Procursus Team <support@procurs.us>
Installed-Size: 217 kB
Depends: libssl3, libplist3 (>= 2.2.0)
Author: Jay Freeman (saurik) <saurik@saurik.com>
Download-Size: 68.3 kB
APT-Manual-Installed: yes
APT-Sources: https://apt.procurs.us iphoneos-arm64/1700/main iphoneos-arm Packages
Description: pseudo-codesign Mach-O files

iPhone:~/permasigner mobile%

**Comment by itsnebulalol** [comment]
The script now checks for ldid in path as well, so remove the ldid binary in the permasigner directory.

It does seem to be a bug with Procursus’ ldid? Not sure how the script would cause that… did it work right before you pulled?

**Comment by FreQRiDeR** [comment]
it did work before I pulled but I had to install libplist3 to make it work. I was getting same error before pulling but libplist3 fixed it. Not so much after pull. I think its a bug in ldid because running it in path with 'ldid' gives same error. Let's see what Procursus Team says about it. I'll keep you posted.

**Comment by itsnebulalol** [comment]
Alright, don't know why it'd start happening after pull

**Comment by FreQRiDeR** [comment]
Also, I deleted ldid from permasigner dir, as you suggested and it prompted to dl ldid again so search for PATH is broken in IOS as ‘ldid’ command succeeds in launching ldid. Who knows?

**Comment by itsnebulalol** [comment]
Closing this as my testing shows i fixed it

**Comment by FreQRiDeR** [comment]
I found this on twitter. That explains why I had to rename libplist3! I guess we have to use ldid in PATH then. Thanks!

![Uploading E3752C12-AFD7-40E7-8907-69E35C5C2593.png…]()
