### ISSUE TITLE
Issue with creating debs on iOS

### ISSUE THREAD

**Issue by Furret-png** [itsnebulalol/permasigner#21]
![A4065BEE-0F52-45C0-9223-0A7A67D47C43](https://user-images.githubusercontent.com/69658166/178091985-dd0a4abe-435e-4922-8dfa-610cc1a3b7cf.jpeg)
There seems to be an issue with it accessing ldid or something. It does end up spitting out a deb in the output folder which installs an app but the app crashes when the phone is not jailbroken. Typing ldid into terminal yields a response though so I’m not sure why it fails when running this program.

**Comment by itsnebulalol** [comment]
Is your installed ldid from procursus?

**Comment by FreQRiDeR** [comment]
I had to install Procursus ldid and libplist3 to get it to work. I copied ldid and dpkg-deb from /usr/bin to permasigner dir. I had to change Owner /Groups to mobile for it to work. Also, ldid was calling for libplist-2.0.3 even though libplist3 was installed. I was able to fix this by duplicating libplist3.dyld in /usr/lib and renaming it libplist-2.0.3.plist. Script works flawlessly now on my iPhone 7, 14.3 Taurine jb!

**Comment by FreQRiDeR** [comment]
![Uploading AE570D28-67FF-45CA-BE21-7BB4F305B842.png…]()

**Comment by itsnebulalol** [comment]
So its the path issue i have to fix... interesting. Thanks for reporting the issue btw!

**Comment by FreQRiDeR** [comment]
Happy to help!
