### ISSUE TITLE
ldid in PATH not found in IOS anymore

### ISSUE THREAD

**Issue by FreQRiDeR** [itsnebulalol/permasigner#27]
Was being recognized in previous main.py version? I had to copy ldid to permasigner dir to make it work again. Just fyi. Thanks.

Term Output:
————————

iPhone:~ mobile% ldid
Link Identity Editor 2.1.5-procursus3

Usage: ldid [-Acputype:subtype] [-a] [-C[adhoc | enforcement | expires | hard |
            host | kill | library-validation | restrict | runtime]] [-D] [-d]
            [-Enum:file] [-e] [-H[sha1 | sha256]] [-h] [-Iname]
            [-Kkey.p12 [-Upassword]] [-M] [-P] [-Qrequirements.xml] [-q]
            [-r | -Sfile.xml | -s] [-u] [-arch arch_type] file ...
Options:
   -S[file.xml]  Pseudo-sign using the entitlements in file.xml
   -Kkey.p12     Sign using private key in key.p12
   -Upassword    Use password to unlock key.p12
   -M            Merge entitlements with any existing
   -h            Print CDHash of file

More information: 'man ldid'
iPhone:~ mobile% cd permasigner
iPhone:~/permasigner mobile% python3 main.py
IPA Permasigner | Version main-2f07502
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[*] ldid not found, downloading.
[?] Would you like to use an IPA stored on the web, or on your system? [external, local]

**Comment by itsnebulalol** [comment]
Oh man, here we go again. Ill see what I can do

**Comment by itsnebulalol** [comment]
Alrighty, can you run `git pull` and then run `python3 main.py --debug`

**Comment by FreQRiDeR** [comment]
iPhone:~ mobile% cd permasigner
iPhone:~/permasigner mobile% python3 main.py --debug
IPA Permasigner | Version main-9e60e99
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[DEBUG] Checking if command ldid is in PATH...
[*] ldid not found, downloading.
[DEBUG] Checking if command dpkg-deb is in PATH...
[?] Would you like to use an IPA stored on the web, or on your system? [external, local]

**Comment by itsnebulalol** [comment]
Try it again

**Comment by FreQRiDeR** [comment]
Nice job! :)
———————

iPhone:~ mobile% cd permasigner
iPhone:~/permasigner mobile% git pull
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), 510 bytes | 46.00 KiB/s, done.
From https://github.com/itsnebulalol/permasigner
   9e60e99..77ff19f  main       -> origin/main
Updating 9e60e99..77ff19f
Fast-forward
 main.py | 13 +++++++++++++
 1 file changed, 13 insertions(+)
iPhone:~/permasigner mobile% python3 main.py --debug
IPA Permasigner | Version main-77ff19f
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[DEBUG] Checking if command ldid is in PATH...
[DEBUG] ldid is installed via dpkg
[DEBUG] Checking if command dpkg-deb is in PATH...
[?] Would you like to use an IPA stored on the web, or on your system? [external, local]

**Comment by itsnebulalol** [comment]
Can you try something for me, remove ldid, run the script and see what it says? You can install it back after

**Comment by FreQRiDeR** [comment]
I’d be happy to. One sec

**Comment by itsnebulalol** [comment]
Thanks!

**Comment by FreQRiDeR** [comment]
iPhone:~ mobile% ldid
zsh: command not found: ldid
iPhone:~ mobile% 
iPhone:~ mobile% cd permasigner
iPhone:~/permasigner mobile% python3 main.py --debug
IPA Permasigner | Version main-77ff19f
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[DEBUG] Checking if command ldid is in PATH...
[-] ldid is required on iOS, but it is not installed. Please install it from Procursus.
iPhone:~/permasigner mobile% 

——————————————
Was gunna say, don’t think you can prompt to curl ios version?

**Comment by itsnebulalol** [comment]
Don't know if I could auto download it, its simple for the user to do it.
Thanks for helping test! You can install ldid back now :)
