### ISSUE TITLE
Compile a version for unc0ver v6.0.2 because jailbreak fails on 6.2.0 for A8 devices

### ISSUE THREAD

**Issue by sapman1208** [itsnebulalol/permasigner#35]
## Context
unc0ver 6.2.0 fails everything when I try to use it on my A8 iPad Air 2. For this reason, I always side loaded 6.0.2.

## Alternatives
Compiling another version for A8 devices would be amazing!

## Has the feature been requested before?
No.

## If the feature request is approved, would you be willing to submit a PR?
Yes

**Comment by itsnebulalol** [comment]
Not exactly sure what you mean, but if you mean make a version that makes u0 work, sadly I can’t. The u0 bug is an issue that pwn20wnd has to fix.

**Comment by itsnebulalol** [comment]
Why did that reopen wtf
