### ISSUE TITLE
The script has errors when the app name has a space in it

### ISSUE THREAD

**Issue by gjk2001** [itsnebulalol/permasigner#40]
For example for the app “Exif Viewer” it gives this error when signing “ldid: /tmp/..../deb/Application/Exif: No such file or directory”. 

Ubuntu 20.04.4 lts

```

```

## Any possible solutions?
Think it’s a quotes issue somewhere

## Version Information
- iOS Version:  14.5
- Jailbreak Name and Version:  Checkn1x-1.1.7

**Comment by FreQRiDeR** [comment]
Copy and paste ipa path or type with “”. Or type Exif\ Viewer, which is appropriate syntax for spaces in command line paths.

**Comment by itsnebulalol** [comment]
Fixed in #44
