### ISSUE TITLE
Bypass install, requirements, when run on ios?

### ISSUE THREAD

**Issue by FreQRiDeR** [itsnebulalol/permasigner#41]
## Context
What are you trying to do, or how would you want to do it differently? Is it something you currently you cannot do? Is this related to an issue/problem?
Error when running on ios.
## Alternatives
Can you achieve the same result doing it in an alternative way? Is the alternative considerable?

## Has the feature been requested before?
Please provide a link to the issue.

## If the feature request is approved, would you be willing to submit a PR?
Yes / No _(Help can be provided if you need assistance submitting a PR)_
———————————————
Unfortunately, script now errors out when running on ios. Is there an easy way to bypass install prompt, requirements when running on ios? Getting sshClient module error. Perhaps if ‘ios’ system then bypass ‘install’ flag etc... That would be great as it was running fantastically on ios before. Or perhaps prompt to install directly from output? That would be cool! 

iPhone:~ mobile% cd permasigner
iPhone:~/permasigner mobile% python3 main.py --debug
Traceback (most recent call last):
  File "/private/var/mobile/permasigner/main.py", line 21, in <module>
    from paramiko.client import AutoAddPolicy, SSHClient
ModuleNotFoundError: No module named 'paramiko'
iPhone:~/permasigner mobile%

**Comment by itsnebulalol** [comment]
You need to rerun `python3 -m pip install -r requirements.txt`

**Comment by FreQRiDeR** [comment]
I did, of course.

**Comment by itsnebulalol** [comment]
Well, the module isn’t installed…

**Comment by FreQRiDeR** [comment]
Yes, probably does not exist for ios?

iPhone:~ mobile% cd permasigner
iPhone:~/permasigner mobile% python3 -m pip install -r require
ments.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: autopep8==1.6.0 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: certifi==2022.6.15 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 2)) (2022.6.15)
Requirement already satisfied: charset-normalizer==2.1.0 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (2.1.0)
Requirement already satisfied: idna==3.3 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (3.3)
Requirement already satisfied: pycodestyle==2.8.0 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (2.8.0)
Requirement already satisfied: requests==2.28.1 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 6)) (2.28.1)
Requirement already satisfied: toml==0.10.2 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (0.10.2)
Requirement already satisfied: urllib3==1.26.9 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 8)) (1.26.9)
Collecting cffi~=1.15.1
  Using cached cffi-1.15.1.tar.gz (508 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/tmp/pip-install-5h6155o3/cffi_2c6381c922cd4ba2a7d97075309a7375/setup.py", line 148, in <module>
          ask_supports_thread()
        File "/private/var/tmp/pip-install-5h6155o3/cffi_2c6381c922cd4ba2a7d97075309a7375/setup.py", line 77, in ask_supports_thread
          config.try_compile('__thread int some_threadlocal_variable_42;'))
        File "/usr/lib/python3.9/distutils/command/config.py", line 223, in try_compile
          self._check_compiler()
        File "/usr/lib/python3.9/distutils/command/config.py", line 99, in _check_compiler
          customize_compiler(self.compiler)
        File "/usr/lib/python3.9/distutils/sysconfig.py", line 200, in customize_compiler
          _osx_support.customize_compiler(_config_vars)
        File "/usr/lib/python3.9/_osx_support.py", line 489, in customize_compiler
          _find_appropriate_compiler(_config_vars)
        File "/usr/lib/python3.9/_osx_support.py", line 244, in _find_appropriate_compiler
          raise SystemError(
      SystemError: Cannot locate working compiler
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
iPhone:~/permasigner mobile%

**Comment by itsnebulalol** [comment]
Yep that seems like the issue, @superrnovae, any ideas how to fix this?

**Comment by superrnovae** [comment]
> Yes, probably does not exist for ios?

It does exist for ios, but the exception prevents it from being installed.
