### ISSUE TITLE
Fails to sign on macOS when using -c flag

### ISSUE THREAD

**Issue by superrnovae** [itsnebulalol/permasigner#45]
## What is the expected behavior?
codesign succeeds

## What is the actual behavior?
codesign fails

## What are the steps to reproduce this bug?
run the script with -s flag

## Please provide debug logs:
Use the `--debug` option while running the script, and paste the output **into the codeblocks**.

```
Signing with codesign as it was specified...
security: SecKeychainItemImport: MAC verification failed during PKCS12 import (wrong password?)
error: The specified item could not be found in the keychain.
[DEBUG] Frameworks path exists
[DEBUG] Executable found in the Module_Framework.framework
Signing executable in Module_Framework.framework
[DEBUG] Running command: codesign -s 'We Do A Little Trolling iPhone OS Application Signing' --force --deep /var/folders/n_/p90183755b30dtf0wcqlh5bc0000gn/T/tmpy7_0nkpx/deb/Applications/YouTube.app/Frameworks/Module_Framework.framework/Module_Framework
error: The specified item could not be found in the keychain.
```

## Any possible solutions?
use correct password

## Can you identify the location in the source code where the problem exists?
[cert import](https://github.com/itsnebulalol/permasigner/blob/main/main.py#L333)

**Comment by superrnovae** [comment]
[Might be related](https://openradar.appspot.com/FB8988319)

**Comment by itsnebulalol** [comment]
Fixed in 7b9b015

**Comment by superrnovae** [comment]
It's now prompting for a password instead.

**Comment by itsnebulalol** [comment]
Alrighty, might make a seperate cert for codesign

**Comment by superrnovae** [comment]
> Codesign is seperate from ldid

I meant that you don't necessarily have to have 2 certs, you can have one that is password protected to use with both ldid and codesign.

**Comment by itsnebulalol** [comment]
I mean yes, but then there’s no support for Elucubratus ldid on iOS

**Comment by itsnebulalol** [comment]
Fixed
