### ISSUE TITLE
Can permasigner be used with a .deb file?

### ISSUE THREAD

**Issue by wakaohhzeh** [itsnebulalol/permasigner#48]
I'm not a dev, just a normal user.
Is there any way to make a .deb file works after losing jailbroken?
Hope it would be a fantastic question for you to upgrade the tool.
Thanks.

**Comment by superrnovae** [comment]
The script only works with ipa files.
If your question is can a tweak packaged as deb work after losing jailbreak the answer is "no".
If the deb file contains an application, than it's contents can be extracted and compressed as ipa.

**Comment by wakaohhzeh** [comment]
Clearly.  Thanks for your response

**Comment by superrnovae** [comment]
> to sign installed ipa’s much like Reprovision?

afaik reprovision can only resign the apps it had previously sideloaded

> Is there a reason permasigner can not be configured
   
Why would you want that?

**Comment by FreQRiDeR** [comment]
To avoid having to download ipa’s again as some are no longer available.

**Comment by superrnovae** [comment]
> To avoid having to download ipa’s again as some are no longer available.
> […](#)
> On Jul 20, 2022, at 10:39 AM, Vladislav ***@***.***> wrote: ﻿ to sign installed ipa’s much like Reprovision? afaik reprovision can only resign the apps it had previously sideloaded Is there a reason permasigner can not be configured Why would you want that? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

In theory this should be possible to implement, I have no idea how to retrieve a list of sideloaded apps from the ios though.

**Comment by itsnebulalol** [comment]
Added support for applications in a .deb in commit bc72a77.
