### ISSUE TITLE
Similar script on redmi note

### ISSUE THREAD

**Issue by martinschultzkristensen** [itsnebulalol/permasigner#5]
Hey,
I have an app I cannot run on my redmi note 7, because it is jailbroken (the app says).
Redmi note runs on LineageOS 18.1

Is there anyway to make a similar script, so this above stated app would work?

thanks for enlightenment 
-Martin

**Comment by syto203** [comment]
Wrong platform. This is for iOS only

**Comment by RexSonic** [comment]
Use Magisk denylist + Universal safetynet fix

**Comment by itsnebulalol** [comment]
Hi there, this script is made for iOS. If you mean you’re trying to run the script on your Android device for your iOS device, that is not officially supported and my not work:
