### ISSUE TITLE
[BUG] ldid in PATH check fails. Dl's ldid.

### ISSUE THREAD

**Issue by FreQRiDeR** [itsnebulalol/permasigner#53]
**Describe the bug**
Checks for ldid in PATH fails and prompts to DL ldid to permasigner directory. Latest ldid from procursus is installed and launches from PATH.
**To reproduce**

1. Run '...'
2. Try and sign '...'
3. See error

**Expected behavior**
use ldid from path. 
**Log**
Use the `--debug` option while running the script, and paste the output **into the codeblocks**.

```
terramoda@terramoda-700T1C:~/permasigner$ python3 main.py --debug
IPA Permasigner | Version main-970cc6e
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking if command dpkg-deb is in PATH...
[*] ldid not found, not from Procursus, or not up to date, downloading latest binary.
[DEBUG] Downloading ldid on Linux x86_64.
[DEBUG] Wrote file.
[?] Would you like to use an external or a local IPA? [E, L] 

----------------------------------------------------------------------------------

terramoda@terramoda-700T1C:~/permasigner$ ldid
Link Identity Editor v2.1.5-procursus5

Usage: ldid [-Acputype:subtype] [-a] [-C[adhoc | enforcement | expires | hard |
            host | kill | library-validation | restrict | runtime]] [-D] [-d]
            [-Enum:file] [-e] [-H[sha1 | sha256]] [-h] [-Iname]
            [-Kkey.p12 [-Upassword]] [-M] [-P[num]] [-Qrequirements.xml] [-q]
            [-r | -Sfile.xml | -s] [-u] [-arch arch_type] file ...
Common Options:
   -S[file.xml]  Pseudo-sign using the entitlements in file.xml
   -Kkey.p12     Sign using private key in key.p12
   -Upassword    Use password to unlock key.p12
   -M            Merge entitlements with any existing
   -h            Print CDHash of file

More information: 'man ldid'
terramoda@terramoda-700T1C:~/permasigner$ 

```

**Which way are you running the script?**
ex. macOS 13.0, Windows with Docker, iOS 14.7.1
any, Linux
**Additional context**
Add any other context about the problem here (ex. can you identify the location in the source code where the problem exists, any possible solutions).
This was fixed a while back. 
**Checklist**

-   [x] All questions were answered if possible.
-   [x] Bug was reproduced atleast 2 times.
-   [x] You are using the latest version of the script (`git pull`).

**Comment by itsnebulalol** [comment]
I removed the ldid path checker, but i forgot to change the error message. I’ll fix that later.

**Comment by itsnebulalol** [comment]
Changed in 932ab0c
