### ISSUE TITLE
Cffi install fail on iOS.

### ISSUE THREAD

**Issue by FreQRiDeR** [itsnebulalol/permasigner#54]
Pip requirements.txt install fails on cffi once again. (Fixed in #45,6 I believe?) I fix this on iOS by simply deleting ‘ utils.installer import Installer, utils.usbmux import USBMux’ from main.py, as they are obviously not needed when signing directly on device. Should we perhaps consider a separate script for iOS? For those of us that wish to permasign directly on their iOS devices?  

Btw, I have clang, dependencies installed however I believe cffi is macOS only? (Not ARM)

————————————————————

iPhone:~ mobile% cd permasigner
iPhone:~/permasigner mobile% python3 -m pip install -r require
ments.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: autopep8==1.6.0 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 1)) (1.6.0)
Collecting bcrypt==3.2.2
  Using cached bcrypt-3.2.2-cp36-abi3-macosx_10_10_universal2.whl (50 kB)
Requirement already satisfied: certifi==2022.6.15 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 3)) (2022.6.15)
Collecting cffi==1.15.1
  Using cached cffi-1.15.1.tar.gz (508 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: charset-normalizer==2.1.0 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (2.1.0)
Collecting cryptography==37.0.4
  Using cached cryptography-37.0.4-cp36-abi3-macosx_10_10_universal2.whl (5.4 MB)
Requirement already satisfied: idna==3.3 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 7)) (3.3)
Collecting paramiko==2.11.0
  Using cached paramiko-2.11.0-py2.py3-none-any.whl (212 kB)
Requirement already satisfied: pycodestyle==2.8.0 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 9)) (2.8.0)
Requirement already satisfied: pycparser==2.21 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 10)) (2.21)
Collecting PyNaCl==1.5.0
  Using cached PyNaCl-1.5.0-cp36-abi3-macosx_10_10_universal2.whl (349 kB)
Requirement already satisfied: requests==2.28.1 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 12)) (2.28.1)
Collecting scp==0.14.4
  Using cached scp-0.14.4-py2.py3-none-any.whl (8.6 kB)
Requirement already satisfied: six==1.16.0 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 14)) (1.16.0)
Requirement already satisfied: toml==0.10.2 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 15)) (0.10.2)
Requirement already satisfied: urllib3==1.26.10 in /private/var/mobile/.local/lib/python3.9/site-packages (from -r requirements.txt (line 16)) (1.26.10)
Using legacy 'setup.py install' for cffi, since package 'wheel' is not installed.
Installing collected packages: cffi, PyNaCl, cryptography, bcrypt, paramiko, scp
  Running setup.py install for cffi ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for cffi did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      ld: library not found for -lSystem
      clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
      Note: will not use '__sync_synchronize()' in the C code
      ***** The above error message can be safely ignored.
      
      running install
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.0-iPhone9,1-3.9
      creating build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/backend_ctypes.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/error.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/setuptools_ext.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/__init__.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/cffi_opcode.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/vengine_gen.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/pkgconfig.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/model.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/ffiplatform.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/api.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/vengine_cpy.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/commontypes.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/lock.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/recompiler.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/cparser.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/verifier.py -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/_cffi_include.h -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/parse_c_type.h -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/_embedding.h -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      copying cffi/_cffi_errors.h -> build/lib.macosx-11.0-iPhone9,1-3.9/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.macosx-11.0-iPhone9,1-3.9
      creating build/temp.macosx-11.0-iPhone9,1-3.9/c
      cc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -DFFI_BUILDING=1 -DUSE__THREAD -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.9 -c c/_cffi_backend.c -o build/temp.macosx-11.0-iPhone9,1-3.9/c/_cffi_backend.o -iwithsysroot/usr/include/ffi
      In file included from c/_cffi_backend.c:2:
      /usr/include/python3.9/Python.h:25:10: fatal error: 'stdio.h' file not found
      #include <stdio.h>
               ^~~~~~~~~
      1 error generated.
      error: command '/usr/bin/cc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> cffi

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
iPhone:~/permasigner mobile%

**Comment by itsnebulalol** [comment]
@superrnovae any alternative to cffi that compiles correctly on iOS?

**Comment by itsnebulalol** [comment]
Also, @FreQRiDeR, please use the issue template next time.

**Comment by FreQRiDeR** [comment]
> Also, @FreQRiDeR, please use the issue template next time.

Sorry, template does not show up in ios? Had to copy/paste from ios terminal. :)

**Comment by FreQRiDeR** [comment]
> @superrnovae any alternative to cffi that compiles correctly on iOS?

I don’t believe cffi is necessary on ios as ipa’s are signed and debs built just fine. Perhaps an if-ios/then bypass install flag? Or prompt install from /mobile/permasigner/output (local) io via ssh? That would be elegant. :)

**Comment by superrnovae** [comment]
easiest solution would be to have 2 requirement files. One for ios and one for macos/linux.

**Comment by itsnebulalol** [comment]
What is cffi a dependency of?

Also, @FreQRiDeR can you check if this is fixed in 106ef44?

**Comment by superrnovae** [comment]
> if this is fixed in [106ef44](https://github.com/itsnebulalol/permasigner/commit/106ef44de18058b9de0a909c042fb8fae1efce81)?

I wasn't trying to fix the dependency on cffi when I pushed this commit.

**Comment by FreQRiDeR** [comment]
> What is cffi a dependency of?
> 
> Also, @FreQRiDeR can you check if this is fixed in [106ef44](https://github.com/itsnebulalol/permasigner/commit/106ef44de18058b9de0a909c042fb8fae1efce81)?

Paramiko, I believe? Will do.

**Comment by itsnebulalol** [comment]
> scp
Doesn't linux/macos come with scp as a terminal utility? Instead of using a python package we could just use the command.

**Comment by FreQRiDeR** [comment]
> > scp
> 
> Doesn't linux/macos come with scp as a terminal utility? Instead of using a python package we could just use the command.

scp is in PATH on my phone.

**Comment by superrnovae** [comment]
Omg, Why am I able to edit other's comments? I have accidentally done that instead of replying. lol.

> Doesn't linux/macos come with scp as a terminal utility? Instead of using a python package we could just use the command.
   

My bad, it's not scp but paramiko that is dependent on it. And I don't think it would be possible to replace it. It made things much much easier to implement, like checking for sudo rights and stuff.

**Comment by itsnebulalol** [comment]
Yeah we wouldn't be able to replace paramiko

**Comment by superrnovae** [comment]
> Yeah we wouldn't be able to replace paramiko

we can replace requirements.txt with a script. And install deps based on the platform it runs on.

**Comment by itsnebulalol** [comment]
Sounds good to me

**Comment by superrnovae** [comment]
On iOS we only need the requests package.

**Comment by FreQRiDeR** [comment]
I don’t seem to have a requirements file? Is it in a different branch? 

Also dpkg, ldid errors now.

Phone:~/permasigner mobile% python3 main.py --debug
IPA Permasigner | Version main-106ef44
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking for ldid on iOS
dpkg-query: warning: parsing file '/Library/dpkg/status' near line 6969 package 'org.cydia.kiimo.carriercrack-global':
 missing 'Description' field
dpkg-query: warning: parsing file '/Library/dpkg/status' near line 6981 package 'org.cydia.kiimo.ccpatch10':
 missing 'Description' field
Package: ldid
Status: install ok installed
Priority: optional
Section: Development
Installed-Size: 216
Maintainer: Procursus Team <support@procurs.us>
Architecture: iphoneos-arm
Version: 2.1.5-procursus5
Depends: libssl3, libplist3 (>= 2.2.0)
Description: pseudo-codesign Mach-O files
Author: Jay Freeman (saurik) <saurik@saurik.com>

dpkg-query: error: --status needs a valid package name but '>' is not: illegal package name in specifier '>': must start with an alphanumeric character

Use --help for help about querying packages.
[-] ldid is required on iOS, but it is not installed. Please install it from Procursus.
iPhone:~/permasigner mobile%

**Comment by itsnebulalol** [comment]
`git pull` and run again

**Comment by superrnovae** [comment]
are you strapped with elucubratus? If that's the case you won't be able to run the script. It's ldid doesn't support password protected certs.

**Comment by itsnebulalol** [comment]
that's procursus ldid

**Comment by FreQRiDeR** [comment]
fixed :)

**Comment by FreQRiDeR** [comment]
Working perfectly now on ios and Linux. (Will check macOS but suspect the same.)
