### ISSUE TITLE
[BUG] Requests not found iOS

### ISSUE THREAD

**Issue by FreQRiDeR** [itsnebulalol/permasigner#56]
**Describe the bug**
After running poetry install, cffi fails as usual. Running main.py fails with ‘requests not found’ error.
**To reproduce**

1. Run 'poetry run python3 main.py —debug'
2. Try and sign '...'
3. See error

**Expected behavior**

**Log**
Use the `--debug` option while running the script, and paste the output **into the codeblocks**.

```

iPhone:~ mobile% cd permasigner
iPhone:~/permasigner mobile% poetry run python3 main.py --debug
Traceback (most recent call last):
  File "/private/var/mobile/permasigner/main.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
iPhone:~/permasigner mobile% 

```

**Which way are you running the script?**
ex. macOS 13.0, Windows with Docker, iOS 14.7.1
iOS 14.3

**Additional context**
Add any other context about the problem here (ex. can you identify the location in the source code where the problem exists, any possible solutions).
What component installs requests module? Is it part of cffi? 

**Checklist**

-   [ ] All questions were answered if possible.
-   [ x] Bug was reproduced atleast 2 times.
-   [ x] You are using the latest version of the script (`git pull`).

**Comment by superrnovae** [comment]
> Is it part of cffi?
   
no. 
   
@itsnebulalol

**Comment by itsnebulalol** [comment]
Please use `poetry install`

**Comment by superrnovae** [comment]
Imo we should move scp stuff to extras

**Comment by superrnovae** [comment]
`git pull` and `poetry update`.

I tested on iOS/Linux.

**Comment by itsnebulalol** [comment]
@superrnovae will be fixed on iOS but now fails on macOS and Linux

I don't want to have people having to run the extra install command but it seems like the only way

**Comment by FreQRiDeR** [comment]
Poetry install installed requests now. Script executes as expected.

**Comment by superrnovae** [comment]
> Poetry install installed requests now. Script executes as expected. 

You can now install permasigner on iOS by simply running `pip install permasigner`.
