### ISSUE TITLE
[BUG] Paramiko,SSHCLIENT Modules not found LinuX

### ISSUE THREAD

**Issue by FreQRiDeR** [itsnebulalol/permasigner#57]
**Describe the bug**
Paramiko, SSHCLIENT Modules not found LinuX
**To reproduce**

1. Run 'poetry run python3 main.py --debug'
2. Try and sign '...'
3. See error

**Expected behavior**

**Log**
Use the `--debug` option while running the script, and paste the output **into the codeblocks**.

```
terramoda@terramoda-700T1C:~/permasigner$ poetry install
Installing dependencies from lock file

No dependencies to install or update
terramoda@terramoda-700T1C:~/permasigner$ poetry update
Updating dependencies
Resolving dependencies... (29.1s)

No dependencies to install or update
terramoda@terramoda-700T1C:~/permasigner$ poetry run python3 main.py --debug
Traceback (most recent call last):
  File "/home/terramoda/permasigner/main.py", line 30, in <module>
    from utils.installer import Installer
  File "/home/terramoda/permasigner/utils/installer.py", line 5, in <module>
    from paramiko.client import AutoAddPolicy, SSHClient
ModuleNotFoundError: No module named 'paramiko'
terramoda@terramoda-700T1C:~/permasigner$ 

```

**Which way are you running the script?**
ex. macOS 13.0, Windows with Docker, iOS 14.7.1
Ubuntu 22.04
**Additional context**
Add any other context about the problem here (ex. can you identify the location in the source code where the problem exists, any possible solutions).

**Checklist**

-   [ ] All questions were answered if possible.
-   [ x] Bug was reproduced atleast 2 times.
-   [ x] You are using the latest version of the script (`git pull`).

**Comment by itsnebulalol** [comment]
@superrnovae

**Comment by itsnebulalol** [comment]
Oh, run `poetry install -E scp`

**Comment by FreQRiDeR** [comment]
CFFI fails on Linux now too?

terramoda@terramoda-700T1C:~/permasigner$ poetry install -E scp
Installing dependencies from lock file

Package operations: 8 installs, 0 updates, 0 removals

  • Installing pycparser (2.21)
  • Installing cffi (1.14.6): Failed

  EnvCommandError

  Command ['/home/terramoda/.cache/pypoetry/virtualenvs/permasigner-g0drJZWO-py3.10/bin/pip', 'install', '--no-deps', '/home/terramoda/.cache/pypoetry/artifacts/2b/51/9a/5dcb4035f05bd9926c007e3368039b00de0e36567299939fe36b218de2/cffi-1.14.6.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/terramoda/.cache/pypoetry/artifacts/2b/51/9a/5dcb4035f05bd9926c007e3368039b00de0e36567299939fe36b218de2/cffi-1.14.6.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'error'
    error: subprocess-exited-with-error
    
    × python setup.py egg_info did not run successfully.
    │ exit code: 1
    ╰─> [14 lines of output]
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/tmp/pip-req-build-2ecdep_g/setup.py", line 148, in <module>
            use_pkg_config()
          File "/tmp/pip-req-build-2ecdep_g/setup.py", line 111, in use_pkg_config
            _ask_pkg_config(include_dirs,       '--cflags-only-I', '-I', sysroot=True)
          File "/tmp/pip-req-build-2ecdep_g/setup.py", line 23, in _ask_pkg_config
            p = subprocess.Popen([pkg_config, option, 'libffi'],
          File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
            self._execute_child(args, executable, preexec_fn, close_fds,
          File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
            raise child_exception_type(errno_num, err_msg, err_filename)
        NotADirectoryError: [Errno 20] Not a directory: 'pkg-config'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.
  

  at ~/.local/lib/python3.10/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│ 
      1197│         return decode(output)
      1198│ 
      1199│     def execute(self, bin, *args, **kwargs):

**Comment by superrnovae** [comment]
Install gcc

**Comment by FreQRiDeR** [comment]
Gcc already latest version.

**Comment by FreQRiDeR** [comment]
> ~ Install pkg-config

same, cffi fails.

**Comment by itsnebulalol** [comment]
Run `git pull` and try to `pip install -r requirements.txt`

**Comment by FreQRiDeR** [comment]
Installing clang fixed it. gcc did not compile requests for some reason?

**Comment by FreQRiDeR** [comment]
you broke it... :100:  :)

terramoda@terramoda-700T1C:~$ cd permasigner
terramoda@terramoda-700T1C:~/permasigner$ git pull
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 50 (delta 31), reused 32 (delta 14), pack-reused 0
Unpacking objects: 100% (50/50), 6.08 KiB | 249.00 KiB/s, done.
From https://github.com/itsnebulalol/permasigner
   70d5746..2c908e9  main       -> origin/main
Updating 70d5746..2c908e9
Fast-forward
 .github/workflows/run.yml  |  10 +-
 .github/workflows/test.yml |  20 +--
 Dockerfile                 |   9 +-
 Dockerfile.development     |   7 +-
 README.md                  |   6 -
 book.json                  |   3 +
 data/docker-entrypoint.sh  |   6 +-
 docs/README.md             |   1 +
 ios_requirements.txt       |   8 ++
 main.py                    |  23 +--
 poetry.lock                | 346 ---------------------------------------------
 pyproject.toml             |  40 ------
 12 files changed, 51 insertions(+), 428 deletions(-)
 create mode 100644 book.json
 create mode 100644 docs/README.md
 create mode 100644 ios_requirements.txt
 delete mode 100644 poetry.lock
 delete mode 100644 pyproject.toml
terramoda@terramoda-700T1C:~/permasigner$ poetry run python3 main.py --debug

  RuntimeError

  Poetry could not find a pyproject.toml file in /home/terramoda/permasigner or its parents

  at ~/.local/lib/python3.10/site-packages/poetry/core/factory.py:369 in locate
      365│             if poetry_file.exists():
      366│                 return poetry_file
      367│ 
      368│         else:
    → 369│             raise RuntimeError(
      370│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371│                     cwd
      372│                 )
      373│             )
terramoda@terramoda-700T1C:~/permasigner$

**Comment by itsnebulalol** [comment]
We switched back to pip

**Comment by FreQRiDeR** [comment]
> We switched back to pip

if it aint broke...

**Comment by itsnebulalol** [comment]
It was broken, Poetry had some weird caching. Just use `pip install -r requirements.txt` or `python3 -m pip install -r ios_requirements.txt` on ios, then run it with `python3 main.py`.
