### ISSUE TITLE
[BUG] AUv3 plugins do not start after installation.

### ISSUE THREAD

**Issue by gjk2001** [itsnebulalol/permasigner#66]
**Describe the bug**
I have tried three different audio units apps.
Apps are signed correctly and install fine. Once installed they do not start.

**To reproduce**

1. Permasign this apps: 
2. Lagrange AUv3 Plugin Synth (v1.2.12) / OBXd AUv3 Synth (v1.11.1) /  OPL AUv3 FM Synth (v2.1.0)
3. Install apps.
4. Try to open installed apps or load as AUv3 in a DAW (Garageband).

**Expected behavior**
Audio Unit can be opened as app or AU plugin in different DAW.
Lagrange start as app but no as AUv3.
OBXd does not start.
OPL does not start.

**Log**
Use the `--debug` option while running the script, and paste the output **into the codeblocks**.

```
user@link:~/permasigner$ python3 main.py --debug
[DEBUG] Using user home directory: /home/user
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking if command dpkg-deb is in PATH...
[DEBUG] Checking if command git is in PATH...
[DEBUG] Git is in PATH
Permasigner | Version main_3744fa8
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[DEBUG] Checking ldid_linux_x86_64 hash...
[DEBUG] ldid hash successfully verified.
[?] Would you like to use an external or a local IPA? [E, L] L

[*] Created temporary directory.

[?] Paste in the path to an IPA in your file system: /home/user/permasigner/IPA no signed/Lagrange AUv3 Plugin Synth (v1.2.12 3GS Univ PI FW 64bit os100 ok14)-user_hidden.bfi2.ipa

[*] Unzipping IPA...

[*] Reading plist...
Found app directory!
Found Info.plist
Found information about the app!

[*] Preparing deb file...
Making directories...
Copying deb file scripts and control...
Copying app files...
Changing deb file scripts permissions...
Changing app executable permissions...

[*] Signing app...
Signing with ldid...
[DEBUG] Running command: /home/user/.permasigner/ldid -S/tmp/tmpusaqcpcn/entitlements.plist -M -Kpermasigner/data/certificate.p12 -Upassword '/tmp/tmpusaqcpcn/deb/Applications/Lagrange.app'

[*] Packaging the deb file...
[DEBUG] Path to deb file: output/Lagrange.deb
[DEBUG] Running command: dpkg-deb -Zxz --root-owner-group -b /tmp/tmpusaqcpcn/deb output/Lagrange.deb
[?] Would you like install the application to your device (must be connected)? [y, n]: n

[*] We are finished!
[*] Copy the newly created deb from the output folder to your jailbroken iDevice and install it!
[*] The app will continue to work when rebooted to stock.
[*] Also, this is free and open source software! Feel free to donate to my Patreon if you enjoy :)
    https://patreon.com/nebulalol
[*] Output file: output/Lagrange.deb
user@beelink:~/permasigner$


```

**Which way are you running the script?**
Ubuntu 20.04 LTS / Permasigner Version main_3744fa8

**Additional context**
Add any other context about the problem here (ex. can you identify the location in the source code where the problem exists, any possible solutions).
 No, sorry
**Checklist**

-   [x] All questions were answered if possible.
-   [x] Bug was reproduced atleast 2 times.
-   [x] You are using the latest version of the script (`git pull`).

**Comment by itsnebulalol** [comment]
@superrnovae any ideas? Seems like there’s another plug-ins folder that isn’t picked up by ldid’s deep sign?

**Comment by superrnovae** [comment]
It'd have to be tested with code sign first to see if it's an issue with procursus's ldid and if so report it to them.

**Comment by itsnebulalol** [comment]
I removed codesign support but I can add it back

**Comment by itsnebulalol** [comment]
@gjk2001 run `git pull` then run `python3 main.py -d -c` and try again. Tell me if it works.

**Comment by gjk2001** [comment]
Hello, the IPAs have been downloaded from iphonecake dot com

**Comment by gjk2001** [comment]
Hello again,

"git pull" show this:

user@link:~/permasigner$ git pull
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (36/36), done.
remote: Total 45 (delta 36), reused 36 (delta 36), pack-reused 9
Unpacking objects: 100% (45/45), 8.53 KiB | 143.00 KiB/s, done.
From https://github.com/itsnebulalol/permasigner
   3744fa8..d99457d  main       -> origin/main
Updating 3744fa8..d99457d
Fast-forward
 bin/permasigner              |  2 ++
 main.py                            |  2 ++
 permasigner/__main__.py      | 73 ++++++++++++++++++++++++++++----------------
 permasigner/ps_downloader.py | 65 +++++++++++++++++++++++----------------
 permasigner/ps_hash.py       | 23 ++++++++------
 permasigner/ps_utils.py      | 35 ++++++++++++---------
 requirements.txt             |  2 +-
 7 files changed, 123 insertions(+), 79 deletions(-)
user@link:~/permasigner$

"python3 main.py -d -c" show this:

user@blink:~/permasigner$ python3 main.py -d -c
[DEBUG] Using user home directory: /home/user
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking if command dpkg-deb is in PATH...
[DEBUG] Checking if command git is in PATH...
[DEBUG] Git is in PATH
Permasigner | Version main_d99457d
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[!] Codesign can only be used on macOS, remove the argument to use ldid instead.
user@link:~/permasigner$

**Comment by itsnebulalol** [comment]
Oh, you’re on Linux…

**Comment by gjk2001** [comment]
I have permasigned all three apps again after doing a git pull.
Now:
Lagrange does not start
OBXd does not start
OPL start as app

**Comment by gjk2001** [comment]
yes, i use linux, could that be the problem?

**Comment by superrnovae** [comment]
> yes, i use linux, could that be the problem?

Could you please upload the iPad to mega or somewhere else, so I can test them with codesign when I get home?

**Comment by gjk2001** [comment]
Yes, I have uploaded them here:
https://file.io/d1Ejj4zFGB5H

**Comment by gjk2001** [comment]
Here is the new link.
https://expirebox.com/LXyFe
The rar password is: Permasigner

**Comment by superrnovae** [comment]
Lagrange Icrashes with EXC_BAD_ACCESS on my arm64 iPad. I suspect it's not compatible with my device due to this key in the Info.plist:   
```
<key>UIRequiredDeviceCapabilities</key>
    <array>
      <string>armv7</string>
```

Can you provide the crash logs? Ldid does seem to sign everything, from plugins to frameworks.

**Comment by itsnebulalol** [comment]
Might add an arg that drops old entitlements and only signs with the new entitlements in the data folder

**Comment by superrnovae** [comment]
I've tried that already. The apps won't start. I don't know why. Logs don't tell much. I don't even know if they work when sideloaded with the altstore. Everything is signed as it's supposed to be.

**Comment by itsnebulalol** [comment]
I mean, the app *is* pirated so

**Comment by superrnovae** [comment]
> I mean, the app _is_ pirated so

it is.
   
OPL is the only app that works.

**Comment by gjk2001** [comment]
If the problem is in the origin of the apps, then it would not be a script bug. This issue could be closed. Anyway, thank you all for such a wonderful job.

**Comment by itsnebulalol** [comment]
No problem
