### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by heinekenpsx** [itsnebulalol/permasigner#77]
Permasigner | Version main_6f5687d
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[?] Would you like to use an external or a local IPA? [E, L] L

[?] Paste in the path to an IPA in your file system: /var/mobile/CloneApp/Appcake_7.2.2-Fix.ipa
[*] Unzipping IPA...

Found app directory!
[*] Reading plist...
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    __main__.main(False)
  File "/private/var/mobile/permasigner/permasigner/__main__.py", line 72, in main
    ps.start()
  File "/private/var/mobile/permasigner/permasigner/__main__.py", line 245, in start
    out_dir = self.run(tmpfolder, ldid_in_path, dpkg_in_path, data_dir)
  File "/private/var/mobile/permasigner/permasigner/__main__.py", line 372, in run
    app_author = app_bundle.split(".")[1]
IndexError: list index out of range
xXx:~/permasigner root#

**Comment by superrnovae** [comment]
Could you please share the IPA?

**Comment by itsnebulalol** [comment]
Here I'm going to assume that the bundle id is 1 word without dots, which is not normal convention for bundle id's.

You can pass the `--bundleid any.text.here` flag to make it build correctly.

**Comment by heinekenpsx** [comment]
> Here I'm going to assume that the bundle id is 1 word without dots, which is not normal convention for bundle id's.
> 
> You can pass the `--bundleid any.text.here` flag to make it build correctly.

Thanks

**Comment by heinekenpsx** [comment]
> Could you please share the IPA?
> 
> It's not a bug in permasigner, rather a mistake by whoever modified the Info.plist

Of course :)
https://github.com/Oct4Pie/appcake-patch

**Comment by superrnovae** [comment]
> Of course :)
> https://github.com/Oct4Pie/appcake-patch

Plist looks fine to me. Can't reproduce it with the latest release.
